joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - JOINT1
      - JOINT2
      - JOINT3

joint1_position_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint : JOINT1

joint2_position_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint : JOINT2

joint3_position_controller:
  type: position_controllers/JointPositionController
  publish_rate: 50
  base_frame_id: base_link
  joint : JOINT3
