fake_joint_driver_node:
  ros__parameters:
    start_position:
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        
      values:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0        